/**************************THIS FILE WAS AUTOGENERATED**************************/
#include <stddef.h>
static char const *user_argv[] = {"clear_your_event_flags", "0", NULL};
static const int user_argc = 2;
/*******************************************************************************/